// Top shows actions

export const TOP_SHOWS_FETCH_START = 'TOP_SHOWS_FETCH_START';
export const TOP_SHOWS_FETCH_SUCCESS = 'TOP_SHOWS_FETCH_SUCCESS';
export const TOP_SHOWS_FETCH_FAIL = 'TOP_SHOWS_FETCH_FAAIL';

// Top movies actions

export const TOP_MOVIES_FETCH_START = 'TOP_MOVIES_FETCH_START';
export const TOP_MOVIES_FETCH_SUCCESS = 'TOP_MOVIES_FETCH_SUCCESS';
export const TOP_MOVIES_FETCH_FAIL = 'TOP_MOVIES_FETCH_FAIL';

// Show details actions

export const SHOW_DETAILS_FETCH_START = 'SHOW_DETAILS_FETCH_START';
export const SHOW_DETAILS_FETCH_SUCCESS = 'SHOW_DETAILS_FETCH_SUCCESS';
export const SHOW_DETAILS_FETCH_FAIL = 'SHOW_DETAILS_FETCH_FAIL';

// Movie details actions
